#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

# Definimos o nome do projeto
name: GameOfThroneApp

# Configuracoes de compilacao
settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)
  
options:
  createIntermediateGroups: True
  bundleIdPrefix: com.dairan
  deploymentTarget:
    iOS: 13.3

targets:
  GameOfThroneApp:
    type: application
    platform: iOS
    sources:
      - GameOfThroneApp
      # - path: TheCatApiApp
        # name: TheCatApiApp
      # - path: TheCatApiApp/Cenas/Home
        # name: Home 
        # excludes: 
          # - "**/Home*.*"
      # - path: Cenas/Home
        # group: Cenas/Home
      # - path: Configurations
      #   group: Build System

    # scheme:
    #   testTargets:
    #   - name: TheCatApiAppTests
    #     randomExecutionOrder: true
    #   gatherCoverageData: true
    #   coverageTargets:
    #     - DeliveryApp
    settings:
      base:
          DEVELOPMENT_TEAM: LSUFS2V6U6
      configs:
        Release:
        Debug:
          ONLY_ACTIVE_ARCH: YES
    info:
      path: GameOfThroneApp/Recursos/Info.plist
      properties:
        UISupportedInterfaceOrientations: []
        NSAppTransportSecurity: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
parallelizeBuild: True
  # TheCatApiAppTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources:
  #     - path: TheCatApiAppTests
  #       includes:
  #         - "**/*.swift"
  #
  #   settings:
  #     TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TheCatApiApp.app/TheCatApiApp"
  #
  #   info:
  #     path: TheCatApiAppTests/Info.plist
# postBuildScripts:
  # - path: Scripts/script.sh
    # name: My Final Script